---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:latest
  environment:
    COVERALL_TOKEN:
      from_secret: COVERALL_TOKEN
  commands:
  - "#"
  - "# installing prerequisites"
  - "#"
  - apt-get update
  - apt-get install -y ninja-build
  - "#"
  - "# compiling"
  - "#"
  - cargo build --verbose --all
  - "#"
  - "# unittests"
  - "#"
  - cargo test --verbose --all
  - "#"
  - "# release compilation"
  - "#"
  - cargo install --path .
  - "#"
  - "# end-to-end tests"
  - "#"
  - make -C src/tests
---
kind: signature
hmac: a2f0426c10d7abe3be88e02c177ffc05bb8445f0ea4b9b8892a9bb0e2510537e

...
