---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rust:latest
    environment:
      COVERALLS_TOKEN:
        from_secret: COVERALL_TOKEN
    commands:
      - "#"
      - "# installing prerequisites"
      - "#"
      - apt-get update
      - apt-get install -y ninja-build python3-requests
      - curl -L https://github.com/mozilla/grcov/releases/download/v0.8.2/grcov-linux-x86_64.tar.bz2 | tar jxf -
        #- cargo install grcov --version 0.6.1
      - rustup toolchain install nightly
      - rustup component add llvm-tools-preview

      - "#"
      - "# compiling with stable rust"
      - "#"
      - cargo build

      - "#"
      - "# stable unittests"
      - "#"
      - cargo test --verbose --all

      - "#"
      - "# stable end-to-end tests"
      - "#"
      - 'LAZE=$(pwd)/target/debug/laze make -C src/tests'

      - "#"
      - "# compiling with nightly rust"
      - "#"
      - cargo +nightly build

      - "#"
      - "# nightly unittests"
      - "#"
      - 'RUSTFLAGS="-Zinstrument-coverage" cargo +nightly test'

      - "#"
      - "# end-to-end tests"
      - "#"
      - 'RUSTFLAGS="-Zinstrument-coverage" LAZE=$(pwd)/target/debug/laze make -C src/tests'

      - "#"
      - "# uploading coverage results"
      - "#"
      - >
        RUSTUP_TOOLCHAIN=nightly
        ./grcov
        $(find . -name default.profraw -print)
        --llvm
        --token $${COVERALLS_TOKEN}
        --commit-sha $${DRONE_COMMIT}
        --service-name drone.schleiser.de
        --service-number $${DRONE_BUILD_NUMBER}
        --vcs-branch $${DRONE_COMMIT_BRANCH}
        --binary-path ./target/debug/laze
        --branch
        --output-path coveralls.json
        --output-type coveralls+
        --source-dir .
        --ignore "/*"

      - python3 dist/coveralls.py coveralls.json
---
kind: signature
hmac: 3f676a54a885253021ba583332f8646aaae41213d8deb4327332aaf85fb99c46

...
