---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:latest
  commands:
  - apt-get update
  - apt-get install -y ninja-build"
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo install --path .
  - make -C src/tests
---
kind: signature
hmac: 2d8b30c684b8e9649629e7cb80c2fbed51acf2b17e392528450b4b357eaf5430

...
