[book]
authors = ["Kaspar Schleiser"]
language = "en"
multilingual = false
src = "src"
title = "laze Manual"
git-repository-url = "https://github.com/kaspar030/laze"
edit-url-template = "https://github.com/kaspar030/laze/edit/master/book/{path}"
