name: container
on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "master"
    tags:
      - "[0-9]+.*.*"

jobs:
  container:
    name: container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # here, "rust" means debian, as that's what the official "rust" images
        # are based on
        os: [ ubuntu, rust ]
        codename: [ latest ]
        include:
          - os: ubuntu
            codename: jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            kaspar030/laze
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},latest=true
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavor: |
            latest=auto
            prefix=
            suffix=${{ matrix.os }}-${{ matrix.codename }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ci/docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DEBIAN_FROM=${{ matrix.os }}:${{ matrix.codename }}
